# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/birlutiuclaudiu/Facultate/An3_sem1/SSC/Laborator/Lab7/BirlutiuClaudiu_Lab7/Exercitii_7.2_7.3_7.4/SPI_mode/SPI_mode.cache/wt [current_project]
set_property parent.project_path /home/birlutiuclaudiu/Facultate/An3_sem1/SSC/Laborator/Lab7/BirlutiuClaudiu_Lab7/Exercitii_7.2_7.3_7.4/SPI_mode/SPI_mode.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/birlutiuclaudiu/Facultate/An3_sem1/SSC/Laborator/Lab7/BirlutiuClaudiu_Lab7/Exercitii_7.2_7.3_7.4/SPI_mode/SPI_mode.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/birlutiuclaudiu/Facultate/An3_sem1/SSC/Laborator/Lab7/BirlutiuClaudiu_Lab7/Exercitii_7.2_7.3_7.4/SPI_mode/SPI_mode.srcs/sources_1/new/SPI_Interface.vhd
  /home/birlutiuclaudiu/Facultate/An3_sem1/SSC/Laborator/Lab7/BirlutiuClaudiu_Lab7/Exercitii_7.2_7.3_7.4/SPI_mode/SPI_mode.srcs/sources_1/imports/new/displ7seg.vhd
  /home/birlutiuclaudiu/Facultate/An3_sem1/SSC/Laborator/Lab7/BirlutiuClaudiu_Lab7/Exercitii_7.2_7.3_7.4/SPI_mode/SPI_mode.srcs/sources_1/imports/new/debounce.vhd
  /home/birlutiuclaudiu/Facultate/An3_sem1/SSC/Laborator/Lab7/BirlutiuClaudiu_Lab7/Exercitii_7.2_7.3_7.4/SPI_mode/SPI_mode.srcs/sources_1/new/Main_ADXL362.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/birlutiuclaudiu/Facultate/An3_sem1/SSC/Laborator/Lab7/BirlutiuClaudiu_Lab7/Exercitii_7.2_7.3_7.4/SPI_mode/SPI_mode.srcs/constrs_1/imports/SSC/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files /home/birlutiuclaudiu/Facultate/An3_sem1/SSC/Laborator/Lab7/BirlutiuClaudiu_Lab7/Exercitii_7.2_7.3_7.4/SPI_mode/SPI_mode.srcs/constrs_1/imports/SSC/Nexys4DDR_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Main_ADXL362 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Main_ADXL362.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Main_ADXL362_utilization_synth.rpt -pb Main_ADXL362_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
