set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[13]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[2]}]
set_property MARK_DEBUG true [get_nets {modul_uart/TxData[0]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[5]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[8]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[11]}]
set_property MARK_DEBUG true [get_nets {modul_uart/St[1]}]
set_property MARK_DEBUG true [get_nets {modul_uart/TSR[1]}]
set_property MARK_DEBUG true [get_nets {modul_uart/TSR[4]}]
set_property MARK_DEBUG true [get_nets {modul_uart/TSR[6]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[30]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[20]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[7]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[9]}]
set_property MARK_DEBUG true [get_nets {modul_uart/St[2]}]
set_property MARK_DEBUG true [get_nets {modul_uart/TSR[9]}]
set_property MARK_DEBUG true [get_nets {modul_uart/TSR[2]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[11]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[7]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[2]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[5]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[25]}]
set_property MARK_DEBUG true [get_nets {modul_uart/TxData[6]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[22]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[15]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[21]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[25]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[29]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[14]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[16]}]
set_property MARK_DEBUG true [get_nets {modul_uart/TSR[5]}]
set_property MARK_DEBUG true [get_nets {modul_uart/St[0]}]
set_property MARK_DEBUG true [get_nets {modul_uart/TSR[7]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[23]}]
set_property MARK_DEBUG true [get_nets {modul_uart/TxData[2]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[28]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[12]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[16]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[22]}]
set_property MARK_DEBUG true [get_nets {modul_uart/TxData[3]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[0]}]
set_property MARK_DEBUG true [get_nets {modul_uart/TxData[4]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[8]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[18]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[23]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[6]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[30]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[4]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[3]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[10]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[17]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[29]}]
set_property MARK_DEBUG true [get_nets {modul_uart/TSR[0]}]
set_property MARK_DEBUG true [get_nets {modul_uart/TSR[3]}]
set_property MARK_DEBUG true [get_nets {modul_uart/TxData[1]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[6]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[1]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[10]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[9]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[4]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[24]}]
set_property MARK_DEBUG true [get_nets {modul_uart/TxData[5]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[12]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[18]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[19]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[21]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[14]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[20]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[24]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[28]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[15]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[31]}]
set_property MARK_DEBUG true [get_nets {modul_uart/TSR[8]}]
set_property MARK_DEBUG true [get_nets modul_uart/Start]
set_property MARK_DEBUG true [get_nets {modul_uart/TxData[7]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[31]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[0]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[3]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[13]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[26]}]
set_property MARK_DEBUG true [get_nets modul_uart/Tx]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[1]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[26]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntBit[27]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[17]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[19]}]
set_property MARK_DEBUG true [get_nets {modul_uart/CntRate[27]}]
set_property MARK_DEBUG true [get_nets modul_uart/TxRdy]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list Clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {modul_uart/CntBit[0]} {modul_uart/CntBit[1]} {modul_uart/CntBit[2]} {modul_uart/CntBit[3]} {modul_uart/CntBit[4]} {modul_uart/CntBit[5]} {modul_uart/CntBit[6]} {modul_uart/CntBit[7]} {modul_uart/CntBit[8]} {modul_uart/CntBit[9]} {modul_uart/CntBit[10]} {modul_uart/CntBit[11]} {modul_uart/CntBit[12]} {modul_uart/CntBit[13]} {modul_uart/CntBit[14]} {modul_uart/CntBit[15]} {modul_uart/CntBit[16]} {modul_uart/CntBit[17]} {modul_uart/CntBit[18]} {modul_uart/CntBit[19]} {modul_uart/CntBit[20]} {modul_uart/CntBit[21]} {modul_uart/CntBit[22]} {modul_uart/CntBit[23]} {modul_uart/CntBit[24]} {modul_uart/CntBit[25]} {modul_uart/CntBit[26]} {modul_uart/CntBit[27]} {modul_uart/CntBit[28]} {modul_uart/CntBit[29]} {modul_uart/CntBit[30]} {modul_uart/CntBit[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {modul_uart/CntRate[0]} {modul_uart/CntRate[1]} {modul_uart/CntRate[2]} {modul_uart/CntRate[3]} {modul_uart/CntRate[4]} {modul_uart/CntRate[5]} {modul_uart/CntRate[6]} {modul_uart/CntRate[7]} {modul_uart/CntRate[8]} {modul_uart/CntRate[9]} {modul_uart/CntRate[10]} {modul_uart/CntRate[11]} {modul_uart/CntRate[12]} {modul_uart/CntRate[13]} {modul_uart/CntRate[14]} {modul_uart/CntRate[15]} {modul_uart/CntRate[16]} {modul_uart/CntRate[17]} {modul_uart/CntRate[18]} {modul_uart/CntRate[19]} {modul_uart/CntRate[20]} {modul_uart/CntRate[21]} {modul_uart/CntRate[22]} {modul_uart/CntRate[23]} {modul_uart/CntRate[24]} {modul_uart/CntRate[25]} {modul_uart/CntRate[26]} {modul_uart/CntRate[27]} {modul_uart/CntRate[28]} {modul_uart/CntRate[29]} {modul_uart/CntRate[30]} {modul_uart/CntRate[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 3 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {modul_uart/St[0]} {modul_uart/St[1]} {modul_uart/St[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 10 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {modul_uart/TSR[0]} {modul_uart/TSR[1]} {modul_uart/TSR[2]} {modul_uart/TSR[3]} {modul_uart/TSR[4]} {modul_uart/TSR[5]} {modul_uart/TSR[6]} {modul_uart/TSR[7]} {modul_uart/TSR[8]} {modul_uart/TSR[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {modul_uart/TxData[0]} {modul_uart/TxData[1]} {modul_uart/TxData[2]} {modul_uart/TxData[3]} {modul_uart/TxData[4]} {modul_uart/TxData[5]} {modul_uart/TxData[6]} {modul_uart/TxData[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list modul_uart/Start]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list modul_uart/Tx]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list modul_uart/TxRdy]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets Clk_IBUF_BUFG]
